### ISSUE TITLE
Hi Jeremy

### ISSUE THREAD

**Issue by trjstewart** [binaryorange/BetterCam#1]
Hi Jeremy,
Sorry for the random issue, I couldn't think of a better way to contact you. I was wondering if you would entertain the chance of transferring ownership of the account name `binaryorage`? I'm trying to start a tiny startup and Binary Orange just happens to be the name I had landed on. It would really mean a lot to me. Feel free to reply here or flick me an email to `tylor@binaryorange.co`.

Thanks mate!

**Comment by binaryorange** [comment]
No.
